services:
  postgres:
    container_name: postgresdb
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - postgresVolume:/var/lib/postgresql

  docker-python:
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  postgresVolume:

